version: "{build}"

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\flowerinthenight\holly

environment:
  GOPATH: c:\gopath

install:  
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build
